### PR TITLE
feat: CLI management command for django

### PR DESCRIPTION
**Pull request by bigpe**
#### Simple use
```bash
./manage.py generate_ts --all
```
Judging by the issue, someone has already done a similar update, but I decided to approach the problem more comprehensively in order to make a universal solution, for me it brought a lot of benefits, I hope it will help others

With this command, we no longer need decorators and, in general, changing our serializer files, however, this functionality has not disappeared anywhere and remains for special cases.

Now we can call the command with the --all flag and get all the generated types to the folder we specified (they will be grouped by the application name, all external applications will be excluded, only the project applications)

We can also generate modules separately, for example -s user will cause generation for all serializers in the user application, and -s user.UserSerializer will cause generation for only one serializer, this is really convenient and cool, now serializers are created only when we need it necessary, not every server restart

All serializers or modules are specified in any quantity, just separated by a space
e.g. ./manage.py generate_ts -s user role.RoleSerializer group

```
--serializers [SERIALIZERS ...], -s [SERIALIZERS ...]
                         Serializers enumeration formats: module_name.SerializerName | module_name
   --all Generate TS types for all project serializers
   --trim, -t Trim "serializer" from type name
   --camelize, -c Camelize field names
   --annotations, -a Add js doc annotations for validations (eg. for Zod)
   --enum_choices, -ec Add choices to external enum type instead union
   --enum_values, -ev Add enum to obtain display name for choices field
```

Here is a list of all options, I want to notice, I added support for all existing options for the generator here, except for mapping_overrides

#### Generate TS for user app
```bash
./manage.py generate_ts -s user
```

#### Generate TS for specific serializer from user app
```bash
./manage.py generate_ts -s user.UserSerializer
```

#### Generate TS for many apps or serializers
```bash
./manage.py generate_ts -s user.UserSerializer group role.RoleSerializer role.RoleListSerializer
```

#### Generate TS for user app with annotations, choices enums, trim serializer, camelize, enum values and custom output path
```bash
./manage.py generate_ts -s user -a -ec -t -c -ev -o "./custom_folder/"
```

#11

### CODE REVIEW

**Comment by bigpe** [comment]
@adenh93 I gave you jobs again, I'm sorry...

**Comment by bigpe** [comment]
@adenh93 It will be cool if you add this functionality to the readme file, it opens up a completely different way to use this library
I tried to describe all the nuances of its use and give all possible examples, I hope this helps

**Comment by adenh93** [comment]
@bigpe Nice, you're knocking it out of the park! This will be an incredibly useful addition. 
I'll merge this one and prepare a release.

**Comment by bigpe** [comment]
@adenh93 We have a problem, the managements folder was not included in the release (missing at pypi), it is an important part of the module, it is there that django will look for the executable commands of the installed application

Another important nuance that I think should be added to the readme, if we want to use the cli, then we need to add django_typomatic to INSTALLED_APPS

It turns out another small unscheduled release...

**Comment by adenh93** [comment]
@bigpe Not a problem, I just had to update `setup.py` to use automatic package discovery and then published a new version. The management subpackage should now be included in the upload from now on! 👍

I also added that update to the README too, good spot!

**Comment by bigpe** [comment]
@adenh93 Dream team...

**Pull request merged**
