### PR TITLE
Improve type handling for PrimaryKeyRelatedField

### PR DESCRIPTION
**Pull request by ghferrari**
The existing code for handling a `PrimaryKeyRelatedField` in a serializer hardcodes the primary key to the union type `number | string`.

This has two disadvantages:

1) The appropriate typescript type can be more narrowly determined by checking the field type of the primary key on the related field. In this way, if the primary key were a string (e.g. a UUID), then it would be better typed as `string` rather than `number | string`. Likewise, if the primary key were a number (e.g. an auto-integer), then it would be better typed as `number` rather than `number | string`.

2) In some cases, the most appropriate typescript for a Django primary key might be neither number nor string. In principle, it could be a `File`. (It could even be a `boolean`, though I imagine there aren't many real life cases of that.)

In this patch, instead of hardcoding the typescript type of a PrimaryKeyRelatedField, we determine what kind of field is being used as the primary key on the related model and then use the existing logic to determine the most appropriate typescript type.

As ever, this pull request is intended as a thank to the author for writing and maintaining this package - thank you!

### CODE REVIEW

**Comment by ghferrari** [comment]
This doesn't quite work - yet. The field type for the primary key on the related field will be of type `<class 'django.db.models.fields.*'>` e.g. `<class 'django.db.models.fields.UUIDField'>`. But there is currently no mapping from django model fields to typescript types. As a result, this patch results in PrimaryKeyRelatedFields being given the `any` type - which is the worst possible outcome. One possible solution would be to add additional mappings in `mappings.py` to ensure that django db model fields can also be mapped to typescript types.

**Comment by ghferrari** [comment]
Following on from my previous message, I've now added mappings for django's db model fields, which I think allows my previous patch to work as intended.

**Comment by adenh93** [comment]
Awesome change @ghferrari! I'll merge this in and release it in the morning! 👌

**Comment by ghferrari** [comment]
Many thanks @adenh93. I'm really enjoying this package - it's doing exactly what I need so I'm happy to be able contribute a little.

**Pull request merged**
