### PR TITLE
Misc bug fixes

### PR DESCRIPTION
**Pull request by biolds**

### CODE REVIEW

**Comment by ghferrari** [comment]
Adding my comment here as a random user of this project (not one of the maintainers...)

The fixes to `django_typomatic/mappings.py` look good to me and correct some errors I made in my earlier pull request - thanks!

I haven't had a chance to assess/test the other fixes, though.

**Comment by adenh93** [comment]
Looks great as usual, @biolds !

Sorry that it's taken me so long to get around to this one, I've been pretty burned out lately 😞 

I'll merge ASAP.

**Comment by adenh93** [comment]
Deployed!

**Comment by biolds** [comment]
Thanks! No worries for the delay!

**Pull request merged**
